### ISSUE TITLE
Flags don't show up correctly on a plane

### ISSUE THREAD

**Issue by Van-Shuimu** [Luke100000/ImmersiveAircraft#125]
Updated from version for MC 1.19.4 to 1.20.1 and this happened.
Flags now are corrupted and do not show up on a plane correctly(
![2024-02-10_00 53 30](https://github.com/Luke100000/ImmersiveAircraft/assets/81547797/06875c62-597d-43d2-a6f8-52d703a9b845)
![2024-02-10_00 53 28](https://github.com/Luke100000/ImmersiveAircraft/assets/81547797/bf0786fe-f8d7-4bf8-a950-200e0a558f9a)

**Comment by Luke100000** [comment]
Most likely fixed in 0.7.4, if not please respond here

**Comment by funkenstxin** [comment]
Unfortunately, still not rendering right on 1.20.1 with 0.7.5. Seems as though it _only_ renders the first layer the banner has on it-- not _all_ of them.

![Screenshot 2024-03-21 18 38 42](https://github.com/Luke100000/ImmersiveAircraft/assets/164427236/65586179-1de7-465b-afcb-419fa1f9b29b)
![Screenshot 2024-03-21 18 38 12](https://github.com/Luke100000/ImmersiveAircraft/assets/164427236/bc023598-0581-42a0-8dd6-e49890afdaa1)

**Comment by Luke100000** [comment]
Interestingly, I can not reconstruct this issue myself.

To make sure we have the exactly same setup, can you try this banner here via give command: https://minecraft.tools/en/banner.php?color_id_0=11&shape_id_1=22&color_id_1=2&shape_id_2=33&color_id_2=12&shape_id_3=26&color_id_3=0&shape_id_4=7&color_id_4=0&shape_id_5=8&color_id_5=0&shape_id_6=36&color_id_6=0#crafting

Also, can you try without shaders in case that breaks.

**Comment by funkenstxin** [comment]
![Screenshot 2024-03-23 14 54 40](https://github.com/Luke100000/ImmersiveAircraft/assets/164427236/6f4b8a83-1098-42ff-9e46-29d1bf3bdc6d)
![Screenshot 2024-03-23 14 54 49](https://github.com/Luke100000/ImmersiveAircraft/assets/164427236/0c7f2160-9c86-4b68-a218-2a38294a4841)

Ran it again with your flag code; minus the shader and the resource pack for Create texturing; same issue. Gonna try it again without AdditionalBanners in this modpack, that's the only other thing I could think of that might be meddling with things.

UPDATE: 
![Screenshot 2024-03-23 15 00 48](https://github.com/Luke100000/ImmersiveAircraft/assets/164427236/8c8d2026-aea3-46e7-83a1-d8b65d73c0a9)

That's without Additional Banners in the pack; which is... Vaguely disappointing. Doesn't throw a fit with shaders, either; which means it was a problem on my end, apologies for the wasted time. Is there a method that could be wrangled for compatibility with custom banner additions like a datapack setup that I don't know about, or are those two just... Destined enemies?

**Comment by kj4lxc** [comment]
We are having the issue as well with our pack [https://www.curseforge.com/minecraft/modpacks/cstmgames-creative-tendencies](https://www.curseforge.com/minecraft/modpacks/cstmgames-creative-tendenciesl)

we are also not using any banner modification mods / datapacks.
